routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


Route::group(['namespace' => 'Auth'], function () {
    Route::get('login', "AdminController@login")->name('auth.admin.login');
    Route::post('login', "AdminController@postLogin")->name('auth.admin.login');
    Route::get('logout', "AdminController@logout")->name('auth.admin.logout');
});


Route::group([ 'namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::get('/', 'AdminController@index')->name('admin.index');

    Route::group(['prefix' => 'users'], function () {
        Route::get('', 'UserController@index')->name('admin.users.index');
        Route::get('create', 'UserController@create')->name('admin.users.create');
        Route::post('create', 'UserController@store')->name('admin.users.store');
        Route::get('edit/{id}', 'UserController@edit')->name('admin.users.edit');
        Route::post('edit/{id}', 'UserController@update')->name('admin.users.update');
        Route::get('destroy/{id}', 'UserController@destroy')->name('admin.users.destroy');

        Route::group(['prefix' => 'profile'], function () {
            Route::get('{id}', 'ProfileController@index')->name('admin.profile.index');
            Route::post('/update/{id}', 'ProfileController@update')->name('admin.profile.update');
        });

        Route::group(['prefix' => 'wallet'], function () {
            Route::get('{id}', 'WalletController@index')->name('admin.wallet.index');
        });

        Route::group(['prefix' => 'refund'], function () {
            Route::get('', 'RefundController@index')->name('admin.refund.index');
            Route::get('delete/{id}', 'RefundController@destroy')->name('admin.refund.destroy');
            Route::get('active', 'RefundController@active')->name('admin.refund.active');
        });
    });

    Route::group(['prefix' => 'product'], function () {
        Route::get('activePost', 'ProductController@activePost')->name('admin.product.activePost');
        Route::get('detail/{id}', 'ProductController@detail')->name('admin.product.detail');
        Route::get('active', 'ProductController@active')->name('admin.product.active');
        Route::get('export', 'ProductController@export')->name('admin.product.export');
        Route::get('importExportView', 'ProductController@importExportView')->name('admin.product.viewimport');
        Route::post('import', 'ProductController@import')->name('admin.product.import');
        Route::get('history', 'ProductController@history')->name('admin.product.history');
    });
    Route::resource('product', 'ProductController', ['as' => 'admin']);
    Route::resource('category', 'CategoryController', ['as' => 'admin']);
    Route::resource('post', 'PostController', ['as' => 'admin']);

    Route::group(['prefix' => 'post'], function () {
        Route::get('active', 'PostController@active')->name('admin.post.active');
    });

    Route::resource('depositrequest', 'DepositRequestController', ['as' => 'admin'])->only([
        'index', 'destroy'
    ]);
    Route::get('active', 'DepositRequestController@active')->name('admin.depositrequest.active');

    Route::resource('notification', 'NotificationController', ['as' => 'admin']);
    Route::resource('informations', 'InforController', ['as' => 'admin']);



});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::pattern('id', '([0-9]*)');
Route::pattern('slug', '(.*)');

Route::group(['namespace' => 'Onekbuy'], function () {
    Route::get('', 'IndexController@index')->name('onekbuy.index.index');
    // Route::get('', 'IndexController@categoryheader')->name('onekbuy.index.categoryheader');
    Route::get('blog', 'PostController@index')->name('onekbuy.post.index');
    Route::get('blog/{slug}/{id}', 'PostController@detail')->name('onekbuy.post.detail');
    Route::get('notice','NoticeController@index')->name('onekbuy.notice.index');

    Route::get('shop', 'ProductController@index')->name('onekbuy.shop.index');
    Route::get('product-category/{slug}','ProductController@index')->name('onekbuy.product.index');
    Route::get('shop/{slug}-{id}', 'ProductController@product')->name('onekbuy.product.product');
    Route::get('shop/xem-pho-bien', 'ProductController@popularProduct')->name('onekbuy.product.popularproduct');
    Route::get('shop/duoc-lua-chon-nhieu-nhat', 'ProductController@mostChosen')->name('onekbuy.product.mostchosen');
    Route::get('shop/de-xuat-hap-dan', 'ProductController@productpropose')->name('onekbuy.product.productpropose');
    Route::get('search-product/', 'ProductController@searchProduct')->name('onekbuy.product.search');
    Route::get('search-blog/', 'PostController@searchBlog')->name('onekbuy.post.search');
    Route::get('shop/sort/{sort}', 'ProductController@sort')->name('onekbuy.product.sort');

    Route::get('notification', 'NotificationController@index')->name('onekbuy.notification.index');
    Route::get('notification/{slug}/{id}', 'NotificationController@show')->name('onekbuy.notification.show');
    Route::get('search-notification/', 'NotificationController@search')->name('onekbuy.notification.search');
   
    Route::get('cau-hoi-thuong-gap', 'IndexController@cauhoi')->name('onekbuy.faq.cauhoi');
    Route::get('gioi-thieu', 'IndexController@gioithieu')->name('onekbuy.faq.gioithieu');
    Route::get('dieu-khoan-su-dung', 'IndexController@dieukhoan')->name('onekbuy.faq.dieukhoan');
    Route::get('chinh-sach-bao-mat', 'IndexController@chinhsach')->name('onekbuy.faq.chinhsach');
    Route::get('chinh-sach-hoan-tien-100', 'IndexController@hoantien')->name('onekbuy.faq.hoantien');
    Route::get('chinh-sach-san-pham-boi-thuong', 'IndexController@boithuong')->name('onekbuy.faq.boithuong');
    Route::get('huong-dan-su-dung-vi-dien-tu', 'IndexController@vidientu')->name('onekbuy.faq.vidientu');


});
Route::group(['namespace' => 'Onekbuy', 'middleware' => 'auth'], function () {
    Route::get('user/info','UserController@info')->name('onekbuy.user.info');
    Route::get('order/{id}','ProductController@order')->name('onekbuy.product.order');
    Route::post('user/info','UserController@postinfo')->name('onekbuy.user.postinfo');
    Route::post('user/depositrequest','UserController@deposit')->name('onekbuy.user.deposit');
    Route::post('user/refund','UserController@refund')->name('onekbuy.user.refund');
    Route::post('user/re_password','UserController@re_password')->name('onekbuy.user.re_password');
});


Route::group([ 'prefix' => 'user', 'namespace' => 'Auth' ], function () {
    Route::get('login', "IndexController@login")->name('auth.index.login');
    Route::post('login', "IndexController@postLogin")->name('auth.index.login');
    Route::get('logout', "IndexController@logout")->name('auth.index.logout');
    Route::post('register',"IndexController@register")->name('auth.mail.register');
    Route::get('forgotpassword', "IndexController@forgotPassword")->name('onekbuy.user.forgotpassword');
    Route::post('forgotpassword', "IndexController@postForgotPassword")->name('onekbuy.user.forgotpassword');
    Route::get('active',"IndexController@active")->name('auth.mail.active');
    Route::get('repassword',"IndexController@repassword")->name('onekbuy.user.repassword');
    Route::get('active-account/{token}',"IndexController@activeAccount")->name('auth.mail.activeAccount');
    Route::get('confirm-password/{token}',"IndexController@confirmPassword")->name('onekbuy.user.confirmPassword');
    Route::post('repassword',"IndexController@postRepassword")->name('onekbuy.user.repassword');
});

app/Models/Information.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Information extends Model
{
    public $table = "informations";
    protected $fillable = [
        'id',
        'phone',
        'address',
        'email',
        'description',
        'logo',
        'header',
    ];
}

resources/views/admin/informations/edit.blade.php
@extends('templates.admin.master')
@section('content')
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Trang Chủ</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Trang chủ</a></li>
                            <li><a href="#">Thông tin</a></li>
                            <li class="active">Thên thông tin</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <!--/.col-->
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header"><strong>Thêm thông tin</strong></div>
                    @include('errors.success')
                    <form action="{{ route('admin.informations.update',$information->id)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="card-body card-block">
                    
                            <div class="form-group">
                                <label for="title" class=" form-control-label">Phone</label>
                                <input type="text" name="phone" class="form-control" value="{{$information->phone}}">
                                <p class="help is-danger" style="color:red;">{{ $errors->first('phone') }}</p>
                            </div>

                            <div class="form-group">
                                <label for="" class=" form-control-label">Address</label>
                                <input type="text" name="address" class="form-control" value="{{$information->address}}">
                                <p class="help is-danger" style="color:red;">{{ $errors->first('address') }}</p>
                            </div>

                            <div class="form-group">
                                <label for="description" class=" form-control-label">Email</label>
                                <input type="text" name="email" class="form-control" value="{{$information->email}}">
                                <p class="help is-danger" style="color:red;">{{ $errors->first('email') }}</p>
                            </div>

                            <div class="form-group">
                                <label for="description" class=" form-control-label">Javascript quản lý</label>
                                <textarea name="header" class="form-control">{{$information->description}}</textarea>
                                <p class="help is-danger" style="color:red;">{{ $errors->first('description') }}</p>
                            </div>

                            <div class="form-group">
                                <label for="">Logo</label>
                                <input type="file" class="form-control-file" name="logo" id="">
                            </div>

                            <div class="form-group">
                                <label for="header" class=" form-control-label">Nội dung</label>
                                <textarea name="description" class="form-control " id="editor1">{!! $information->header!!}</textarea>
                                <p class="help is-danger" style="color:red;">{{ $errors->first('header') }}</p>
                            </div>
                             
                            <button type="submit" class="btn btn-primary">Sửa</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div><!-- .animated -->
</div>
<script>
    var options = {
      filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
      filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
      filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
      filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
    };
</script>
<script>
    CKEDITOR.replace('editor1', options);
</script>

<script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
<script>
$('textarea.editor1').ckeditor(options);
</script>
@endsection