routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


Route::group(['namespace' => 'Auth'], function () {
    Route::get('login', "AdminController@login")->name('auth.admin.login');
    Route::post('login', "AdminController@postLogin")->name('auth.admin.login');
    Route::get('logout', "AdminController@logout")->name('auth.admin.logout');
});


Route::group([ 'namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::get('/', 'AdminController@index')->name('admin.index');

    Route::group(['prefix' => 'users'], function () {
        Route::get('', 'UserController@index')->name('admin.users.index');
        Route::get('create', 'UserController@create')->name('admin.users.create');
        Route::post('create', 'UserController@store')->name('admin.users.store');
        Route::get('edit/{id}', 'UserController@edit')->name('admin.users.edit');
        Route::post('edit/{id}', 'UserController@update')->name('admin.users.update');
        Route::get('destroy/{id}', 'UserController@destroy')->name('admin.users.destroy');

        Route::group(['prefix' => 'profile'], function () {
            Route::get('{id}', 'ProfileController@index')->name('admin.profile.index');
            Route::post('/update/{id}', 'ProfileController@update')->name('admin.profile.update');
        });

        Route::group(['prefix' => 'wallet'], function () {
            Route::get('{id}', 'WalletController@index')->name('admin.wallet.index');
        });

        Route::group(['prefix' => 'refund'], function () {
            Route::get('', 'RefundController@index')->name('admin.refund.index');
            Route::get('delete/{id}', 'RefundController@destroy')->name('admin.refund.destroy');
            Route::get('active', 'RefundController@active')->name('admin.refund.active');
        });
    });

    Route::group(['prefix' => 'product'], function () {
        Route::get('activePost', 'ProductController@activePost')->name('admin.product.activePost');
        Route::get('detail/{id}', 'ProductController@detail')->name('admin.product.detail');
        Route::get('active', 'ProductController@active')->name('admin.product.active');
        Route::get('export', 'ProductController@export')->name('admin.product.export');
        Route::get('importExportView', 'ProductController@importExportView')->name('admin.product.viewimport');
        Route::post('import', 'ProductController@import')->name('admin.product.import');
        Route::get('history', 'ProductController@history')->name('admin.product.history');
    });
    Route::resource('product', 'ProductController', ['as' => 'admin']);
    Route::resource('category', 'CategoryController', ['as' => 'admin']);
    Route::resource('post', 'PostController', ['as' => 'admin']);

    Route::group(['prefix' => 'post'], function () {
        Route::get('active', 'PostController@active')->name('admin.post.active');
    });

    Route::resource('depositrequest', 'DepositRequestController', ['as' => 'admin'])->only([
        'index', 'destroy'
    ]);
    Route::get('active', 'DepositRequestController@active')->name('admin.depositrequest.active');

    Route::resource('notification', 'NotificationController', ['as' => 'admin']);
    Route::resource('informations', 'InforController', ['as' => 'admin']);



});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::pattern('id', '([0-9]*)');
Route::pattern('slug', '(.*)');

Route::group(['namespace' => 'Onekbuy'], function () {
    Route::get('', 'IndexController@index')->name('onekbuy.index.index');
    // Route::get('', 'IndexController@categoryheader')->name('onekbuy.index.categoryheader');
    Route::get('blog', 'PostController@index')->name('onekbuy.post.index');
    Route::get('blog/{slug}/{id}', 'PostController@detail')->name('onekbuy.post.detail');
    Route::get('notice','NoticeController@index')->name('onekbuy.notice.index');

    Route::get('shop', 'ProductController@index')->name('onekbuy.shop.index');
    Route::get('product-category/{slug}','ProductController@index')->name('onekbuy.product.index');
    Route::get('shop/{slug}-{id}', 'ProductController@product')->name('onekbuy.product.product');
    Route::get('shop/xem-pho-bien', 'ProductController@popularProduct')->name('onekbuy.product.popularproduct');
    Route::get('shop/duoc-lua-chon-nhieu-nhat', 'ProductController@mostChosen')->name('onekbuy.product.mostchosen');
    Route::get('shop/de-xuat-hap-dan', 'ProductController@productpropose')->name('onekbuy.product.productpropose');
    Route::get('search-product/', 'ProductController@searchProduct')->name('onekbuy.product.search');
    Route::get('search-blog/', 'PostController@searchBlog')->name('onekbuy.post.search');
    Route::get('shop/sort/{sort}', 'ProductController@sort')->name('onekbuy.product.sort');

    Route::get('notification', 'NotificationController@index')->name('onekbuy.notification.index');
    Route::get('notification/{slug}/{id}', 'NotificationController@show')->name('onekbuy.notification.show');
    Route::get('search-notification/', 'NotificationController@search')->name('onekbuy.notification.search');
   
    Route::get('cau-hoi-thuong-gap', 'IndexController@cauhoi')->name('onekbuy.faq.cauhoi');
    Route::get('gioi-thieu', 'IndexController@gioithieu')->name('onekbuy.faq.gioithieu');
    Route::get('dieu-khoan-su-dung', 'IndexController@dieukhoan')->name('onekbuy.faq.dieukhoan');
    Route::get('chinh-sach-bao-mat', 'IndexController@chinhsach')->name('onekbuy.faq.chinhsach');
    Route::get('chinh-sach-hoan-tien-100', 'IndexController@hoantien')->name('onekbuy.faq.hoantien');
    Route::get('chinh-sach-san-pham-boi-thuong', 'IndexController@boithuong')->name('onekbuy.faq.boithuong');
    Route::get('huong-dan-su-dung-vi-dien-tu', 'IndexController@vidientu')->name('onekbuy.faq.vidientu');


});
Route::group(['namespace' => 'Onekbuy', 'middleware' => 'auth'], function () {
    Route::get('user/info','UserController@info')->name('onekbuy.user.info');
    Route::get('order/{id}','ProductController@order')->name('onekbuy.product.order');
    Route::post('user/info','UserController@postinfo')->name('onekbuy.user.postinfo');
    Route::post('user/depositrequest','UserController@deposit')->name('onekbuy.user.deposit');
    Route::post('user/refund','UserController@refund')->name('onekbuy.user.refund');
    Route::post('user/re_password','UserController@re_password')->name('onekbuy.user.re_password');
});


Route::group([ 'prefix' => 'user', 'namespace' => 'Auth' ], function () {
    Route::get('login', "IndexController@login")->name('auth.index.login');
    Route::post('login', "IndexController@postLogin")->name('auth.index.login');
    Route::get('logout', "IndexController@logout")->name('auth.index.logout');
    Route::post('register',"IndexController@register")->name('auth.mail.register');
    Route::get('forgotpassword', "IndexController@forgotPassword")->name('onekbuy.user.forgotpassword');
    Route::post('forgotpassword', "IndexController@postForgotPassword")->name('onekbuy.user.forgotpassword');
    Route::get('active',"IndexController@active")->name('auth.mail.active');
    Route::get('repassword',"IndexController@repassword")->name('onekbuy.user.repassword');
    Route::get('active-account/{token}',"IndexController@activeAccount")->name('auth.mail.activeAccount');
    Route::get('confirm-password/{token}',"IndexController@confirmPassword")->name('onekbuy.user.confirmPassword');
    Route::post('repassword',"IndexController@postRepassword")->name('onekbuy.user.repassword');
});

app/Models/Notification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
    protected $table = 'notification';
    protected $fillable = [
        'titel',
        'slug',
        'description',
        'image',
    ];
}

app/Http/Controllers/Admin/NotificationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Notification;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use Validator;

class NotificationController extends Controller
{
    public function index()
    {
        $notifications = Notification::paginate(10);
        return view('admin.notification.index', compact('notifications'));
    }

    public function create()
    {
        return view('admin.notification.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|min:6|unique:notification,title',
            'description' => 'required',
            'content' => 'required',
            'image' => 'required|mimes:jpeg,jpg,png,gif',
        ], [
            'title.required' => 'Bạn cần nhập tiều đề',
            'title.unique' => 'Tiều đề đã tồn tại',
            'title.min' => 'Tiều đề tối thiểu 6 ký tự',
            'description.required' => 'Bạn cần nhập mô tả',
            'content.required' => 'Bạn cần nhập nội dung',
            'image.required' => 'Bạn tải hình ảnh lên',
            'image.mimes:jpeg,jpg,png,gif' => 'Bạn cần tải hình ảnh đúng định dạng jpg, jpeg, png, gif',
        ]);

        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        }  
        $notification = new Notification;
        $notification->title = $request->title;
        $notification->slug = Str::slug($request->title);
        $notification->description = $request->description;
        $notification->content = $request->content;
        $notification->excel = '';
        if ($request->file('image') != '') {
            $path = public_path('upload/images/');
            $file_old = $path . $notification->image;
            if(File::exists($file_old)) {
                File::delete($file_old); 
            }
            
            $file = $request->file('image');
            $filename = time().$file->getClientOriginalName();
            $file->move('./upload/images/', $filename);
            $notification->image = $filename;
        } 
        if ($request->file('excel') != '') {
            $path = public_path('upload/excel/');
            $file_old = $path . $notification->excel;
            if(File::exists($file_old)) {
                File::delete($file_old); 
            }
            
            $file = $request->file('excel');
            $filename = time().$file->getClientOriginalName();
            $file->move('./upload/excel/', $filename);
            $notification->excel = $filename;
        } 
        $notification->save();
        return back()->with('success', 'Thêm thông báo thành công!');
    }

    public function edit($id)
    {
        $notification = Notification::findOrFail($id);
        return view('admin.notification.edit', compact('notification'));
    }

    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|min:6|unique:notification,title,'. $id,
            'description' => 'required',
            'content' => 'required',
            'image' => 'mimes:jpeg,jpg,png,gif',
        ], [
            'title.required' => 'Bạn cần nhập tiều đề',
            'title.unique' => 'Tiều đề đã tồn tại',
            'title.min' => 'Tiều đề tối thiểu 6 ký tự',
            'description.required' => 'Bạn cần nhập mô tả',
            'content.required' => 'Bạn cần nhập nội dung',
            'image.mimes:jpeg,jpg,png,gif' => 'Bạn cần tải hình ảnh đúng định dạng jpg, jpeg, png, gif',
        ]);
        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        } 
        $notification = Notification::findOrFail($id);
        $notification->title = $request->title;
        $notification->slug = Str::slug($request->title);
        $notification->description = $request->description;
        $notification->content = $request->content;
        $notification->excel = $request->excel;
        if ($request->file('image') != '') {
            $path = public_path('upload/images/');
            $file_old = $path . $notification->image;
            if(File::exists($file_old)) {
                File::delete($file_old); 
            }
            
            $file = $request->file('image');
            $filename = time().$file->getClientOriginalName();
            $file->move('./upload/images/', $filename);
            $notification->image = $filename;
        } 
        if ($request->file('excel') != '') {
            $path = public_path('upload/excel/');
            $file_old = $path . $notification->excel;
            if(File::exists($file_old)) {
                File::delete($file_old); 
            }
            
            $file = $request->file('excel');
            $filename = time().$file->getClientOriginalName();
            $file->move('./upload/excel/', $filename);
            $notification->excel = $filename;
        } 
        $notification->save();
        return back()->with('success', 'Cập nhật thông báo thành công!');
        
    }

    public function destroy($id)
    {
        $notification = Notification::findOrFail($id);
        $notification->delete();
        return response()->json([
            'message' => 'Xóa thông báo thành công!'
        ]);
    }
}

app/Http/Controllers/Onekbuy/NotificationController.php
<?php

namespace App\Http\Controllers\Onekbuy;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Notification;

class NotificationController extends Controller
{
    public function index()
    {
        $notifications = Notification::paginate(20);
        return view('onekbuy.notification.index', compact('notifications'));
    }

    public function show($slug, $id)
    {
        $notification = Notification::findOrFail($id);
        $previous = notification::where('id', '<', $notification->id)->orderBy('id','desc')->first();
        $next = notification::where('id', '>', $notification->id)->orderBy('id')->first();
        return view('onekbuy.notification.detail',compact('notification', 'previous', 'next'));
    }

    public function search(Request $request)
    {
        $search = Notification::where('title','LIKE','%'.$request->title.'%')->orderby('id','desc')->paginate(8);
        return view('onekbuy.notification.search',compact('search'));
    }
}

resources/views/admin/notification/create.blade.php
@extends('templates.admin.master')
@section('content')
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Trang chủ</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Trang chủ</a></li>
                            <li><a href="#">Thông báo</a></li>
                            <li class="active">Thên thông báo</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <!--/.col-->
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header"><strong>Thêm thông báo</strong></div>
                    @include('errors.success')
                    <form action="{{ route('admin.notification.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="card-body card-block">
                    
                            <div class="form-group">
                                <label for="title" class=" form-control-label">Tiêu đề</label>
                                <input type="text" name="title" class="form-control" value="{{ old('title')}}">
                                @if ($errors->has('title'))
                                    <span class="text-danger">{{ $errors->first('title') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="description" class=" form-control-label">Mô tả</label>
                                <input type="text" name="description" class="form-control" value="{{ old('description')}}">
                                @if ($errors->has('description'))
                                    <span class="text-danger">{{ $errors->first('description') }}</span>
                                @endif
                            </div>
                            
                            <div class="form-group">
                                <label for="content" class=" form-control-label">Nội dung</label>
                                <textarea name="content" class="form-control " id="editor1">{!! old('content')!!}</textarea>
                                @if ($errors->has('content'))
                                    <span class="text-danger">{{ $errors->first('content') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="">Ảnh</label>
                                <input type="file" class="form-control-file" name="image" >
                                @if ($errors->has('image'))
                                    <span class="text-danger">{{ $errors->first('image') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="">File excel</label>
                                <input type="file" class="form-control-file" name="excel" accept=".xlsx, .xls, .csv">
                                @if ($errors->has('excel'))
                                    <span class="text-danger">{{ $errors->first('excel') }}</span>
                                @endif
                            </div>
                            <button type="submit" class="btn btn-primary">Thêm</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div><!-- .animated -->
</div>
<script>
    var options = {
      filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
      filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
      filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
      filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
    };
</script>
<script>
    CKEDITOR.replace('editor1', options);
</script>

<script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
<script>
$('textarea.editor1').ckeditor(options);
</script>
@endsection

resources/views/admin/notification/edit.blade.php
@extends('templates.admin.master')
@section('content')
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Trang chủ</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Trang chủ</a></li>
                            <li><a href="#">Thông báo</a></li>
                            <li class="active">Sửa thông báo</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <!--/.col-->
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header"><strong>Sửa thông báo</strong></div>
                    @include('errors.success')
                    <form action="{{ route('admin.notification.update', $notification->id)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="card-body card-block">
                    
                            <div class="form-group">
                                <label for="title" class=" form-control-label">Tiêu đề</label>
                                <input type="text" name="title" class="form-control" value="{{ $notification->title}}">
                                @if ($errors->has('title'))
                                    <span class="text-danger">{{ $errors->first('title') }}</span>
                                @endif
                            </div>
                            
                            <div class="form-group">
                                <label for="description" class=" form-control-label">Mô tả</label>
                                <input type="text" name="description" class="form-control" value="{{ $notification->description }}">
                                @if ($errors->has('description'))
                                    <span class="text-danger">{{ $errors->first('description') }}</span>
                                @endif
                            </div>
                            
                            <div class="form-group">
                                <label for="content" class=" form-control-label">Nội dung</label>
                                <textarea name="content" class="form-control " id="editor1">{!! $notification->content !!}</textarea>
                                @if ($errors->has('content'))
                                    <span class="text-danger">{{ $errors->first('content') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="">Ảnh</label>
                                <img style="width: 150px" src="{{ asset('upload/images/'. $notification->image)}}" alt="">
                                <input type="file" class="form-control-file" name="image" id="">
                                @if ($errors->has('content'))
                                    <span class="text-danger">{{ $errors->first('image') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="">File excel</label>
                                <input type="file" class="form-control-file" name="excel" accept=".xlsx, .xls, .csv">
                                @if ($errors->has('excel'))
                                    <span class="text-danger">{{ $errors->first('excel') }}</span>
                                @endif
                            </div>
                            <button type="submit" class="btn btn-primary">Cập nhật</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div><!-- .animated -->
</div>
<script>
    var options = {
      filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
      filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
      filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
      filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
    };
</script>
<script>
    CKEDITOR.replace('editor1', options);
</script>

<script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
<script>
$('textarea.editor1').ckeditor(options);
</script>
@endsection

resources/views/admin/notification/index.blade.php
@extends('templates.admin.master')
@section('content')
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Trang chủ</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Trang chủ</a></li>
                            <li><a href="#" class="active">Thông báo</a></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Quản lý thông báo</strong>
                    </div>
                    <div class="card-header">
                        <a href="{{ route('admin.notification.create')}}" class="btn btn-success">Thêm</a>
                    </div>
                    <div class="">
                        <p class="mb-0 text-white" id="success"></p>
                    </div>
                    @include('errors.error')
                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Hình ảnh</th>
                                    <th>Tiêu đề</th>
                                    <th>Mô tả</th>
                                    <th>Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($notifications as $item)
                                    <tr id="tableId{{$item->id}}">
                                        <td>#{{ $item->id }} </td>
                                        <td><img style="width: 100px" src="{{ asset('upload/images/'. $item->image)}}" alt=""></td>
                                        <td><a href="">{{ $item->title}}</a> </td>
                                        <td>{{ $item->description}}</td>
                                        <td>
                                            <a href="{{ route('admin.notification.edit', $item->id)}}" class="btn btn-info">Sửa</a>
                                            <a href="" data-toggle="modal" data-target="#modelId{{$item->id}}" class="btn btn-danger">Xóa</a>
                                            <!-- Button trigger modal -->
                                            
                                            <!-- Modal -->
                                            <div class="modal fade" id="modelId{{$item->id}}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title">Bạn có châc chắn xóa thông báo này không?</h5>
                                                        </div>
                                                        
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                                                            <a href="{{ route('admin.notification.destroy', $item->id)}}" class="btn btn-danger deleteNotification" data-id="{{ $item->id }}" data-dismiss="modal">Xóa</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{ $notifications->links() }}
                    </div> <!-- /.table-stats -->
                </div>
            </div>
        </div>
    </div><!-- .animated -->
</div>
<div class="clearfix"></div>
@endsection
@section('javascript')
    <script src="{{ asset('asset/admin/assets/js/adminJs/notification.js')}}"></script>
@endsection