routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


Route::group(['namespace' => 'Auth'], function () {
    Route::get('login', "AdminController@login")->name('auth.admin.login');
    Route::post('login', "AdminController@postLogin")->name('auth.admin.login');
    Route::get('logout', "AdminController@logout")->name('auth.admin.logout');
});


Route::group([ 'namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::get('/', 'AdminController@index')->name('admin.index');

    Route::group(['prefix' => 'users'], function () {
        Route::get('', 'UserController@index')->name('admin.users.index');
        Route::get('create', 'UserController@create')->name('admin.users.create');
        Route::post('create', 'UserController@store')->name('admin.users.store');
        Route::get('edit/{id}', 'UserController@edit')->name('admin.users.edit');
        Route::post('edit/{id}', 'UserController@update')->name('admin.users.update');
        Route::get('destroy/{id}', 'UserController@destroy')->name('admin.users.destroy');

        Route::group(['prefix' => 'profile'], function () {
            Route::get('{id}', 'ProfileController@index')->name('admin.profile.index');
            Route::post('/update/{id}', 'ProfileController@update')->name('admin.profile.update');
        });

        Route::group(['prefix' => 'wallet'], function () {
            Route::get('{id}', 'WalletController@index')->name('admin.wallet.index');
        });

        Route::group(['prefix' => 'refund'], function () {
            Route::get('', 'RefundController@index')->name('admin.refund.index');
            Route::get('delete/{id}', 'RefundController@destroy')->name('admin.refund.destroy');
            Route::get('active', 'RefundController@active')->name('admin.refund.active');
        });
    });

    Route::group(['prefix' => 'product'], function () {
        Route::get('activePost', 'ProductController@activePost')->name('admin.product.activePost');
        Route::get('detail/{id}', 'ProductController@detail')->name('admin.product.detail');
        Route::get('active', 'ProductController@active')->name('admin.product.active');
        Route::get('export', 'ProductController@export')->name('admin.product.export');
        Route::get('importExportView', 'ProductController@importExportView')->name('admin.product.viewimport');
        Route::post('import', 'ProductController@import')->name('admin.product.import');
        Route::get('history', 'ProductController@history')->name('admin.product.history');
    });
    Route::resource('product', 'ProductController', ['as' => 'admin']);
    Route::resource('category', 'CategoryController', ['as' => 'admin']);
    Route::resource('post', 'PostController', ['as' => 'admin']);

    Route::group(['prefix' => 'post'], function () {
        Route::get('active', 'PostController@active')->name('admin.post.active');
    });

    Route::resource('depositrequest', 'DepositRequestController', ['as' => 'admin'])->only([
        'index', 'destroy'
    ]);
    Route::get('active', 'DepositRequestController@active')->name('admin.depositrequest.active');

    Route::resource('notification', 'NotificationController', ['as' => 'admin']);
    Route::resource('informations', 'InforController', ['as' => 'admin']);



});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::pattern('id', '([0-9]*)');
Route::pattern('slug', '(.*)');

Route::group(['namespace' => 'Onekbuy'], function () {
    Route::get('', 'IndexController@index')->name('onekbuy.index.index');
    // Route::get('', 'IndexController@categoryheader')->name('onekbuy.index.categoryheader');
    Route::get('blog', 'PostController@index')->name('onekbuy.post.index');
    Route::get('blog/{slug}/{id}', 'PostController@detail')->name('onekbuy.post.detail');
    Route::get('notice','NoticeController@index')->name('onekbuy.notice.index');

    Route::get('shop', 'ProductController@index')->name('onekbuy.shop.index');
    Route::get('product-category/{slug}','ProductController@index')->name('onekbuy.product.index');
    Route::get('shop/{slug}-{id}', 'ProductController@product')->name('onekbuy.product.product');
    Route::get('shop/xem-pho-bien', 'ProductController@popularProduct')->name('onekbuy.product.popularproduct');
    Route::get('shop/duoc-lua-chon-nhieu-nhat', 'ProductController@mostChosen')->name('onekbuy.product.mostchosen');
    Route::get('shop/de-xuat-hap-dan', 'ProductController@productpropose')->name('onekbuy.product.productpropose');
    Route::get('search-product/', 'ProductController@searchProduct')->name('onekbuy.product.search');
    Route::get('search-blog/', 'PostController@searchBlog')->name('onekbuy.post.search');
    Route::get('shop/sort/{sort}', 'ProductController@sort')->name('onekbuy.product.sort');

    Route::get('notification', 'NotificationController@index')->name('onekbuy.notification.index');
    Route::get('notification/{slug}/{id}', 'NotificationController@show')->name('onekbuy.notification.show');
    Route::get('search-notification/', 'NotificationController@search')->name('onekbuy.notification.search');
   
    Route::get('cau-hoi-thuong-gap', 'IndexController@cauhoi')->name('onekbuy.faq.cauhoi');
    Route::get('gioi-thieu', 'IndexController@gioithieu')->name('onekbuy.faq.gioithieu');
    Route::get('dieu-khoan-su-dung', 'IndexController@dieukhoan')->name('onekbuy.faq.dieukhoan');
    Route::get('chinh-sach-bao-mat', 'IndexController@chinhsach')->name('onekbuy.faq.chinhsach');
    Route::get('chinh-sach-hoan-tien-100', 'IndexController@hoantien')->name('onekbuy.faq.hoantien');
    Route::get('chinh-sach-san-pham-boi-thuong', 'IndexController@boithuong')->name('onekbuy.faq.boithuong');
    Route::get('huong-dan-su-dung-vi-dien-tu', 'IndexController@vidientu')->name('onekbuy.faq.vidientu');


});
Route::group(['namespace' => 'Onekbuy', 'middleware' => 'auth'], function () {
    Route::get('user/info','UserController@info')->name('onekbuy.user.info');
    Route::get('order/{id}','ProductController@order')->name('onekbuy.product.order');
    Route::post('user/info','UserController@postinfo')->name('onekbuy.user.postinfo');
    Route::post('user/depositrequest','UserController@deposit')->name('onekbuy.user.deposit');
    Route::post('user/refund','UserController@refund')->name('onekbuy.user.refund');
    Route::post('user/re_password','UserController@re_password')->name('onekbuy.user.re_password');
});


Route::group([ 'prefix' => 'user', 'namespace' => 'Auth' ], function () {
    Route::get('login', "IndexController@login")->name('auth.index.login');
    Route::post('login', "IndexController@postLogin")->name('auth.index.login');
    Route::get('logout', "IndexController@logout")->name('auth.index.logout');
    Route::post('register',"IndexController@register")->name('auth.mail.register');
    Route::get('forgotpassword', "IndexController@forgotPassword")->name('onekbuy.user.forgotpassword');
    Route::post('forgotpassword', "IndexController@postForgotPassword")->name('onekbuy.user.forgotpassword');
    Route::get('active',"IndexController@active")->name('auth.mail.active');
    Route::get('repassword',"IndexController@repassword")->name('onekbuy.user.repassword');
    Route::get('active-account/{token}',"IndexController@activeAccount")->name('auth.mail.activeAccount');
    Route::get('confirm-password/{token}',"IndexController@confirmPassword")->name('onekbuy.user.confirmPassword');
    Route::post('repassword',"IndexController@postRepassword")->name('onekbuy.user.repassword');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = "products";
    protected $fillable  = [
        'category_id',
        'name',
        'slug',
        'description',
        'ship',
        'price',
        'promotion_price',
        'image',
        'active'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsToMany('App\User');
    }

    public function imagesProduct()
    {   
        return $this->hasMany(ImagesProduct::class);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Product;
use App\Models\ImagesProduct;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use App\Imports\ProductsImport;
use App\Exports\ProductsExport;
use App\Models\Post;
use Maatwebsite\Excel\Facades\Excel;

class ProductController extends Controller

{
    public function index()
    {
        $products = Product::orderBy('id', 'desc')->paginate(10);
        return view('admin.product.index', compact('products'));
    }
    
    public function create()
    {
        $categories = Category::all();
        return view('admin.product.create', compact('categories'));
    }
    
    public function active(Request $request)
    {
        $id = $request->id;
        $product = Product::findOrFail($id);
        if ($product->active == 0) {
            $product->active = 1;
            $product->save();
            return '<a href="javascript:void(0)" onclick="getActive('.$id.')" style="cursor: pointer"><i class="fa fa-check text-success"></i> </a>';
        } else {
            $product->active= 0;
            $product->save();
            return '<a href="javascript:void(0)" onclick="getActive('.$id.')" style="cursor: pointer"><i class="fa fa-close text-danger"></i> </a>';
        }
    }
    public function activePost(Request $request){
        $id = $request->id;
        $post = Post::findOrFail($id);
        if ($post->active == 0) {
            $post->active = 1;
            $post->save();
            return '<a href="javascript:void(0)" onclick="getActive('.$id.')" style="cursor: pointer"><i class="fa fa-check text-success"></i> </a>';
        } else {
            $post->active= 0;
            $post->save();
            return '<a href="javascript:void(0)" onclick="getActive('.$id.')" style="cursor: pointer"><i class="fa fa-close text-danger"></i> </a>';
        }
    }
    
    public function store(Request $request)
    {   
        $product = new Product();
        $validator = Validator::make($request->all(), [
            'name' => 'required|unique:products',
            'description' => 'required',
            'ship'=>'required',
            'price' => 'required',
            'promotion_price' => 'required',
            'image' => 'required',
            'files' => 'required'
        ]);

        if ($validator->fails()) {
            if ($validator->fails()) {
                return back()->withErrors($validator)->withInput();
            } 
        }

        $product->category_id  = $request->category_id; 
        $product->name  = $request->name; 
        $product->slug  = Str::slug($request->name); 
        $product->description  = $request->description; 
        $product->ship =$request->ship;
        $product->price  = $request->price; 
        $product->promotion_price  = $request->promotion_price; 
  


        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $filename = time().$file->getClientOriginalName();
            $file->move('./upload/images/', $filename);
            $product->image = $filename;
        } 
       
        $product->save();

        if ($request->hasFile('image')) {
            foreach($request->file('files') as $item){
                $addpicture = New ImagesProduct();
                $name= $item->getClientOriginalName();
                $item->move(public_path().'/upload/', $name);  
                $addpicture->image_name = $name;
                $addpicture->alt = $product->name;
                $addpicture->product_id = $product->id;
                $addpicture->save();
            }
        }
        return back()->with('success', 'Thêm sản phẩm thành công!');
    }

    public function edit($id)
    {
        $product = Product::findOrFail($id);
        $categories = Category::all();
        return view('admin.product.edit', compact('product', 'categories'));
    }

    public function update(Request $request, $id)
    {
        $product = Product::findOrFail($id);

        $validator = Validator::make($request->all(), [
            'name' => 'unique:products,name,'. $id,
        ]);
            
        if ($validator->fails()) {
            if ($validator->fails()) {
                return back()->withErrors($validator)->withInput();
            } 
        }

        $product->category_id  = $request->category_id; 
        $product->name  = $request->name; 
        $product->slug  = Str::slug($request->name); 
        $product->description  = $request->description; 
        $product->ship =$request->ship;
        $product->price  = $request->price; 
        $product->promotion_price  = $request->promotion_price; 
        
        if ($request->file('image') != '') {
            $path = public_path('upload/images/');
            $file_old = $path . $product->image;
            if(File::exists($file_old)) {
                File::delete($file_old); 
            }
            
            $file = $request->file('image');
            $filename = time().$file->getClientOriginalName();
            $file->move('./upload/images/', $filename);
            $product->image = $filename;
        } 
        $product->save();
        return redirect()->route('admin.product.index')->with('success', 'Cập nhật sản phẩm thành công!');
    }
    
    public function destroy(Request $request,$id)
    {
        $product = Product::findOrFail($id);
        $path = public_path('upload/images/');
        $file_old = $path . $product->image;
        if(File::exists($file_old)) {
            File::delete($file_old); 
        }
        $product->delete();
        return response()->json([
            'message' => 'Xóa sản phẩm thành công!'
          ]);
    }

    public function importExportView()
    {
       return view('admin.product.import');
    }
   
    public function import() 
    {
        if (!(request()->hasFile('import'))) {
            return back()->with('error', 'Bạn chưa chọn file!');
        }
        Excel::import(new ProductsImport,request()->file('import'));
        return back()->with('success', 'Nhập dữ liệu sản phẩm từ file excel thành công!');
    }

    public function export() 
    {
        return Excel::download(new ProductsExport, 'products.xlsx');
    }

    public function detail($id)
    {
        $product = Product::with('user')->find($id);
        return view('admin.product.detail', compact('product'));
    }
}

resources/views/admin/product/create.blade.php
@extends('templates.admin.master')
@section('content')
<style type="text/css">
    input[type="file"] {
      display: block;
    }
    .imageThumb {
      height: 120px;
      width: 100px;
      border: 2px solid;
      padding: 1px;
      cursor: pointer;
      object-fit: cover
    }
    .pip {
      display: inline-block;
      margin: 10px 10px 0 0;
    }
    .remove {
      display: block;
      background: #444;
      border: 1px solid black;
      color: white;
      text-align: center;
      cursor: pointer;
    }
    .remove:hover {
      background: white;
      color: black;
    }
</style>
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Trang chủ</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Trang chủ</a></li>
                            <li><a href="#">Sản phẩm</a></li>
                            <li class="active">Thên sản phẩm</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <!--/.col-->
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header"><strong>Thêm sản phẩm</strong></div>
                    @include('errors.success')
                    <form action="{{ route('admin.product.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="card-body card-block">
                            <div class="form-group">
                              <label for="">Danh mục sản phẩm</label>
                              <select class="form-control px-18 py-0" name="category_id" id="">
                                  @foreach ($categories as $item)
                                    <option value="{{$item->id}}">{{ $item->name}}</option>
                                  @endforeach
                              </select>
                            </div>
                            <div class="form-group">
                                <label for="street" class=" form-control-label">Tên sản phẩm</label>
                                <input type="text" name="name" class="form-control" value="{{ old('name')}}">
                                @if ($errors->has('name'))
                                    <span class="text-danger">{{ $errors->first('name') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="description" class=" form-control-label">Mô tả</label>
                                <textarea name="description" class="form-control " id="editor1">{!! old('description')!!}</textarea>
                                @if ($errors->has('description'))
                                    <span class="text-danger">{{ $errors->first('description') }}</span>
                                @endif
                            </div>
                            
                            <div class="form-group">
                                <label for="price" class=" form-control-label">Ship</label>
                                <input type="text" name="ship" class="form-control" value="{{ old('ship')}}">
                                @if ($errors->has('ship'))
                                    <span class="text-danger">{{ $errors->first('ship') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="price" class=" form-control-label">Giá</label>
                                <input type="text" name="price" class="form-control" value="{{ old('price')}}">
                                @if ($errors->has('price'))
                                    <span class="text-danger">{{ $errors->first('price') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="promotion_price" class=" form-control-label">Giá khuyến mãi</label>
                                <input type="number" name="promotion_price" class="form-control" value="{{ old('promotion_price')}}">
                                @if ($errors->has('promotion_price'))
                                    <span class="text-danger">{{ $errors->first('promotion_price') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                              <label for="">Ảnh sản phẩm</label>
                              
                              <input type="file" class="form-control-file" name="image" id="">
                            </div>
                            <div class="form-group">
                                <label class="control-label">Ảnh slide:</label>
                                <div class="field" align="left">
                                  <input type="file" id="files" name="files[]" multiple />
                                </div>
                              </div>
                            <button type="submit" class="btn btn-primary">Thêm</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div><!-- .animated -->
</div>

<script>
    var options = {
      filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
      filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
      filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
      filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
    };
</script>
<script>
    CKEDITOR.replace('editor1', options);
</script>

<script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
<script>
$('textarea.editor1').ckeditor(options);
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      if (window.File && window.FileList && window.FileReader) {
        $("#files").on("change", function(e) {
          var files = e.target.files,
            filesLength = files.length;
          for (var i = 0; i < filesLength; i++) {
            var f = files[i]
            var fileReader = new FileReader();
            fileReader.onload = (function(e) {
              var file = e.target;
              $("<span class=\"pip\">" +
                "<img class=\"imageThumb\" width='100px' src=\"" + e.target.result + "\" title=\"" + file.name + "\"/>" +
                "<br/><span class=\"remove\">Remove image</span>" +
                "</span>").insertAfter("#files");
              $(".remove").click(function(){
                $(this).parent(".pip").remove();
              });
              
              
            });
            fileReader.readAsDataURL(f);
          }
        });
      } else {
        alert("Your browser doesn't support to File API")
      }
    });
</script>
@endsection

resources/views/admin/product/detail.blade.php
@extends('templates.admin.master')
@section('content')
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Trang chủ</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Trang chủ</a></li>
                            <li><a href="#" class="active">Sản phẩm</a></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <strong class="card-title">Quản lý sản phẩm</strong>
                    </div>

                    <div class="">
                        <p class="mb-0 text-white" id="success"></p>
                    </div>
                    @include('errors.error')
                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Ảnh</th>
                                    <th>Tên sản phẩm</th>
                                    <th>Danh mục sản phẩm</th>
                                    <th>Giá</th>
                                    <th>Trạng thái</th>
                                    <th>Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                    <tr id="tableId{{$product->id}}">
                                        <td>#{{ $product->id }} </td>
                                        <td><img src="{{ asset('upload/images/'. $product->image)}}" width="100px"  alt=""></td>
                                        <td style="width: 400px"><a href="">{{ $product->name}}</a> </td>
                                        <td>{{ $product->category->name}}</td>
                                        <td><p>{{ number_format($product->price)}} VND</p></td>
                                        <td id="active-{{ $product->id }}"> 
                                            @if ($product->active == 1)
                                              <a href="javascript:void(0)" onclick="getActive({{$product->id}})" style="cursor: pointer"><i class="fa fa-check text-success"></i> </a>
                                            @else
                                              <a href="javascript:void(0)" onclick="getActive({{$product->id}})" style="cursor: pointer"><i class="fa fa-close text-danger"></i></a>
                                            @endif
                                          </td>
                                        
                                        <td>
                                            <a href="{{ route('admin.product.edit', $product->id)}}" class="btn btn-info">Sửa</a>
                                            <a href="" data-toggle="modal" data-target="#modelId{{$product->id}}" class="btn btn-danger">Xóa</a>
                                            <!-- Modal -->
                                            <div class="modal fade" id="modelId{{$product->id}}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title">Bạn có châc chắn xóa tài khoản này không?</h5>
                                                        </div>
                                                        
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                                                            <a  href="{{ route('admin.product.destroy',$product->id) }}" class="btn btn-danger deleteProduct" id="deleteProduct{{$product->id}}" data-id="{{ $product->id }}" data-dismiss="modal">Xóa</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                            </tbody>
                        </table>
                    </div> <!-- /.table-stats -->

                </div>
            </div>
            <div class="col-lg-1">
            </div>
            <div class="col-lg-10">
                <div class="card">
                    <div class="card-body">
                        <strong class="card-title">Quản lý người dùng đã đặt lệnh</strong>
                    </div>

                    <div class="">
                        <p class="mb-0 text-white" id="success"></p>
                    </div>
                    @include('errors.error')
                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Họ và tên</th>
                                    <th>Email</th>
                                    <th>Địa chỉ</th>
                                    <th>Số điện thoại</th>
                                </tr>
                            </thead>
                            <tbody>
                            	@foreach($product->user as $item)
                                    <tr id="{{$item->id}}">
                                        <td>{{ $item->id }} </td>
                                        <td>{{ $item->profile->fullname }} </td>
                                        <td>{{ $item->email }} </td>
                                        <td>{{ $item->profile->address }} </td>
                                        <td>{{ $item->profile->phone_number }} </td>
                                       
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div> <!-- /.table-stats -->
                    
                </div>
            </div>
        </div>
    </div><!-- .animated -->
</div>
<div class="clearfix"></div>


@endsection
@section('javascript')
    <script src="{{ asset('asset/admin/assets/js/adminJs/product.js')}}"></script>
@endsection