routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


Route::group(['namespace' => 'Auth'], function () {
    Route::get('login', "AdminController@login")->name('auth.admin.login');
    Route::post('login', "AdminController@postLogin")->name('auth.admin.login');
    Route::get('logout', "AdminController@logout")->name('auth.admin.logout');
});


Route::group([ 'namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::get('/', 'AdminController@index')->name('admin.index');

    Route::group(['prefix' => 'users'], function () {
        Route::get('', 'UserController@index')->name('admin.users.index');
        Route::get('create', 'UserController@create')->name('admin.users.create');
        Route::post('create', 'UserController@store')->name('admin.users.store');
        Route::get('edit/{id}', 'UserController@edit')->name('admin.users.edit');
        Route::post('edit/{id}', 'UserController@update')->name('admin.users.update');
        Route::get('destroy/{id}', 'UserController@destroy')->name('admin.users.destroy');

        Route::group(['prefix' => 'profile'], function () {
            Route::get('{id}', 'ProfileController@index')->name('admin.profile.index');
            Route::post('/update/{id}', 'ProfileController@update')->name('admin.profile.update');
        });

        Route::group(['prefix' => 'wallet'], function () {
            Route::get('{id}', 'WalletController@index')->name('admin.wallet.index');
        });

        Route::group(['prefix' => 'refund'], function () {
            Route::get('', 'RefundController@index')->name('admin.refund.index');
            Route::get('delete/{id}', 'RefundController@destroy')->name('admin.refund.destroy');
            Route::get('active', 'RefundController@active')->name('admin.refund.active');
        });
    });

    Route::group(['prefix' => 'product'], function () {
        Route::get('activePost', 'ProductController@activePost')->name('admin.product.activePost');
        Route::get('detail/{id}', 'ProductController@detail')->name('admin.product.detail');
        Route::get('active', 'ProductController@active')->name('admin.product.active');
        Route::get('export', 'ProductController@export')->name('admin.product.export');
        Route::get('importExportView', 'ProductController@importExportView')->name('admin.product.viewimport');
        Route::post('import', 'ProductController@import')->name('admin.product.import');
        Route::get('history', 'ProductController@history')->name('admin.product.history');
    });
    Route::resource('product', 'ProductController', ['as' => 'admin']);
    Route::resource('category', 'CategoryController', ['as' => 'admin']);
    Route::resource('post', 'PostController', ['as' => 'admin']);

    Route::group(['prefix' => 'post'], function () {
        Route::get('active', 'PostController@active')->name('admin.post.active');
    });

    Route::resource('depositrequest', 'DepositRequestController', ['as' => 'admin'])->only([
        'index', 'destroy'
    ]);
    Route::get('active', 'DepositRequestController@active')->name('admin.depositrequest.active');

    Route::resource('notification', 'NotificationController', ['as' => 'admin']);
    Route::resource('informations', 'InforController', ['as' => 'admin']);



});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::pattern('id', '([0-9]*)');
Route::pattern('slug', '(.*)');

Route::group(['namespace' => 'Onekbuy'], function () {
    Route::get('', 'IndexController@index')->name('onekbuy.index.index');
    // Route::get('', 'IndexController@categoryheader')->name('onekbuy.index.categoryheader');
    Route::get('blog', 'PostController@index')->name('onekbuy.post.index');
    Route::get('blog/{slug}/{id}', 'PostController@detail')->name('onekbuy.post.detail');
    Route::get('notice','NoticeController@index')->name('onekbuy.notice.index');

    Route::get('shop', 'ProductController@index')->name('onekbuy.shop.index');
    Route::get('product-category/{slug}','ProductController@index')->name('onekbuy.product.index');
    Route::get('shop/{slug}-{id}', 'ProductController@product')->name('onekbuy.product.product');
    Route::get('shop/xem-pho-bien', 'ProductController@popularProduct')->name('onekbuy.product.popularproduct');
    Route::get('shop/duoc-lua-chon-nhieu-nhat', 'ProductController@mostChosen')->name('onekbuy.product.mostchosen');
    Route::get('shop/de-xuat-hap-dan', 'ProductController@productpropose')->name('onekbuy.product.productpropose');
    Route::get('search-product/', 'ProductController@searchProduct')->name('onekbuy.product.search');
    Route::get('search-blog/', 'PostController@searchBlog')->name('onekbuy.post.search');
    Route::get('shop/sort/{sort}', 'ProductController@sort')->name('onekbuy.product.sort');

    Route::get('notification', 'NotificationController@index')->name('onekbuy.notification.index');
    Route::get('notification/{slug}/{id}', 'NotificationController@show')->name('onekbuy.notification.show');
    Route::get('search-notification/', 'NotificationController@search')->name('onekbuy.notification.search');
   
    Route::get('cau-hoi-thuong-gap', 'IndexController@cauhoi')->name('onekbuy.faq.cauhoi');
    Route::get('gioi-thieu', 'IndexController@gioithieu')->name('onekbuy.faq.gioithieu');
    Route::get('dieu-khoan-su-dung', 'IndexController@dieukhoan')->name('onekbuy.faq.dieukhoan');
    Route::get('chinh-sach-bao-mat', 'IndexController@chinhsach')->name('onekbuy.faq.chinhsach');
    Route::get('chinh-sach-hoan-tien-100', 'IndexController@hoantien')->name('onekbuy.faq.hoantien');
    Route::get('chinh-sach-san-pham-boi-thuong', 'IndexController@boithuong')->name('onekbuy.faq.boithuong');
    Route::get('huong-dan-su-dung-vi-dien-tu', 'IndexController@vidientu')->name('onekbuy.faq.vidientu');


});
Route::group(['namespace' => 'Onekbuy', 'middleware' => 'auth'], function () {
    Route::get('user/info','UserController@info')->name('onekbuy.user.info');
    Route::get('order/{id}','ProductController@order')->name('onekbuy.product.order');
    Route::post('user/info','UserController@postinfo')->name('onekbuy.user.postinfo');
    Route::post('user/depositrequest','UserController@deposit')->name('onekbuy.user.deposit');
    Route::post('user/refund','UserController@refund')->name('onekbuy.user.refund');
    Route::post('user/re_password','UserController@re_password')->name('onekbuy.user.re_password');
});


Route::group([ 'prefix' => 'user', 'namespace' => 'Auth' ], function () {
    Route::get('login', "IndexController@login")->name('auth.index.login');
    Route::post('login', "IndexController@postLogin")->name('auth.index.login');
    Route::get('logout', "IndexController@logout")->name('auth.index.logout');
    Route::post('register',"IndexController@register")->name('auth.mail.register');
    Route::get('forgotpassword', "IndexController@forgotPassword")->name('onekbuy.user.forgotpassword');
    Route::post('forgotpassword', "IndexController@postForgotPassword")->name('onekbuy.user.forgotpassword');
    Route::get('active',"IndexController@active")->name('auth.mail.active');
    Route::get('repassword',"IndexController@repassword")->name('onekbuy.user.repassword');
    Route::get('active-account/{token}',"IndexController@activeAccount")->name('auth.mail.activeAccount');
    Route::get('confirm-password/{token}',"IndexController@confirmPassword")->name('onekbuy.user.confirmPassword');
    Route::post('repassword',"IndexController@postRepassword")->name('onekbuy.user.repassword');
});

app/Models/DepositRequest.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DepositRequest extends Model
{
    protected $table = "depositrequest";
    protected $fillable = [
        'id',
        'name',
        'email',
        'phone',
        'payment',
        'money',
        'message',
        'status',
        'user_id',
    ];

    public function user(){
        return $this->belongsTo('App\User', 'user_id');
    }
}

app/Http/Controllers/Admin/DepositRequestController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\DepositRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use App\User;

class DepositRequestController extends Controller
{
    public function index()
    {
        $depositrequest = DepositRequest::orderBy('id', 'desc')->paginate(10);
        return view('admin.depositrequest.index', compact('depositrequest'));
    }

    public function active(Request $request)
    {
        $id = $request->id;
        $depositrequest = DepositRequest::findOrFail($id);
        if ($depositrequest->status == 0) {
            $depositrequest->status = 1;
            $depositrequest->save();
            $wallet = User::findOrFail($depositrequest->user_id)->wallet;
            $wallet->credit_total += $depositrequest->money;
            $wallet->save();
            $data  = [  
                'id' => $depositrequest->id,
                'name' => $depositrequest->name, 
                'email' => $depositrequest->email, 
                'wallet' => $wallet->credit_total
            ];
            Mail::send('admin.depositrequest.mail',array('data' => $data),function($message) use ($data){
                $message->to($data['email'], $data['name'] )->subject('1kbuy');
            });
            return '<span class="badge badge-complete">Chấp nhận</span>';
        } else {
            $depositrequest->status= 0;
            $depositrequest->save();
            return '<a href="javascript:void(0)" onclick="getActive('.$id.')" style="cursor: pointer"><span class="badge badge-danger">Chưa chấp nhận</span> </a>';
        }
    }

    public function destroy($id)
    {
        $depositrequest = DepositRequest::findOrFail($id);
        $depositrequest->delete();
        return response()->json([
            'message' => 'Xóa yêu cầu nạp tiền thành công!'
        ]);
    }
}

resources/views/admin/depositrequest/index.blade.php
@extends('templates.admin.master')
@section('content')
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Trang chủ</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Trang chủ</a></li>
                            <li><a href="#" class="active">Nạp tiền</a></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <strong class="card-title">Quản lý yêu cầu nạp tiền</strong>
                    </div>
                    @include('errors.error')
                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Tên</th>
                                    <th>Số điện thoại</th>
                                    <th>Email</th>
                                    <th>Phương thức thanh toán</th>
                                    <th>Sô tài khoản</th>
                                    <th>Số tiền</th>
                                    <th>Lời nhắn</th>
                                    <th>Trạng thái</th>
                                    <th>Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($depositrequest as $item)
                                    <tr id="depositrequesttable{{$item->id}}">
                                        <td>#{{ $item->id }} </td>
                                        <td>{{ $item->name}} </td>
                                        <td>{{ $item->phone}} </td>
                                        <td>{{ $item->email}} </td>
                                        <td>{{ $item->payment}} </td>
                                        <td>{{ $item->account_number}} </td>
                                        <td><span class="product">{{ number_format($item->money)}} VND</span> </td>
                                        <td>{{ $item->message}} </td>
                                        <td id="depositrequestActive-{{ $item->id }}"> 
                                            @if ($item->status == 1)
                                              <span class="badge badge-complete">Đã xác nhận</span>
                                            @else
                                              <a href="javascript:void(0)" onclick="getActive({{$item->id}})" style="cursor: pointer"><span class="badge badge-danger">Chưa xác nhận</span></a>
                                            @endif
                                          </td>
                                        
                                        <td>
                                            <a href="" data-toggle="modal" data-target="#modelId{{$item->id}}" class="btn btn-danger">Xóa</a>
                                            <!-- Modal -->
                                            <div class="modal fade" id="modelId{{$item->id}}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title">Bạn có châc chắn xóa yêu cầu nạp tièn này không?</h5>
                                                        </div>
                                                        
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                                                            <a  href="{{ route('admin.depositrequest.destroy',$item->id) }}" class="btn btn-danger depositrequest" id="depositrequest{{$item->id}}" data-id="{{ $item->id }}" data-dismiss="modal">Xóa</a></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{ $depositrequest->links() }}
                    </div> <!-- /.table-stats -->
                </div>
            </div>
        </div>
    </div><!-- .animated -->
</div>
<div class="clearfix"></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    function getActive(id){
       $.ajax({
         url: "{{route('admin.depositrequest.active')}}",
         type: 'GET',
         cache: false,
         data: {
               id: id,
           },
         success: function(data){
           console.log('success')
           $('#depositrequestActive-'+id).html(data);
         },
         error: function() {
          alert("Có lỗi");
        }
      });
       return false;
     }
</script>
@endsection
@section('javascript')
    <script src="{{ asset('asset/admin/assets/js/adminJs/depositrequest.js')}}"></script>
@endsection

resources/views/admin/depositrequest/mail.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Init HTML</title>
    <link rel="stylesheet" href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'
        >
</head>
<body style="margin: 0; padding: 0;">
    <div
        style="background: #FAFBFC; margin: 0px; min-height: 300px; padding: 0px 30px 15px; font-family: ‘Open+Sans’, ‘Open Sans’, Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.5;">
        <div style="max-width: 700px; margin: 0 auto;">
            <div style="text-align: center; padding-bottom: 20px; padding-top: 30px;">
                <span style="font-weight: 700; font-size: 32px; color: #000;">Nạp tiền thành công!</span>
            </div>
            <div style="border-top: 3px solid #B1E0E6; color: #525C65; padding: 10px; background: #fff;">
            <p style="margin: 5px 0;color: #525C65">Xin chào bạn {{ $data['name']}}!</p>
                <p style="margin: 5px 0;color: #525C65">Yêu cầu nạp tiền của bạn đã được xác nhận</p>
                <p style="margin: 5px 0;color: #525C65">Số dư của tài khoản : {{ number_format($data['wallet'])}} đ</p>
            </div>
            <div >
            </div>
            <div class="" style="text-align: center">
                <a href="{{ route('onekbuy.index.index') }}">
                <button type="button"
                        style="background-color:#B1E0E6!important;border-color: #B1E0E6 ;
                        margin-top:0px; margin-bottom:20px;padding: .375rem .75rem; font-size: 1rem;
                        border-radius: .25rem;border: 1px solid transparent;">Trang chủ
                </button>
                </a>
            </div>
            <div style="text-align: center;"><img style="max-width: 100%;" 
                    src="https://www.inithtml.com/demo/email/shadow.png" alt="Shadow"></div>
            <div style="text-align: center; margin-top: 45px; margin-bottom: 45px;">
                <div style="margin-bottom: 30px;">
                    <a href="#" style="margin-right: 20px;"><img alt=""
                            src="https://image.flaticon.com/icons/svg/1384/1384053.svg" width="26" height="26"></a>
                    <a href="#" style="margin-right: 20px"><img alt=""
                            src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Facebook_icon_2013.svg/300px-Facebook_icon_2013.svg.png"
                            width="26" height="26"></a>
                </div>
            </div>
        </div>
    </div>
    <div
        style="text-align: center; background:#B1E0E6; padding: 10px 0; color: #fff; font-family: ‘Open+Sans’, ‘Open Sans’, Helvetica, Arial, sans-serif; font-size: 14px;">
        Cảm ơn bạn!</div>
</body>
</html>